PUT multistep/
Content-Type: application/json

{

  "settings" : {
    "number_of_shards" : 1
  },
  "mappings" : {
    "properties" : {
        "my_field": {"type": "text"}
    }
  }
}

---

POST multistep/_doc
Content-Type: application/json

{
   "my_field": "value #1"
}

---

POST multistep/_doc
Content-Type: application/json

{
   "my_field": "# value 2"
}
